### ISSUE TITLE
Header parsing does not work as expected

### ISSUE THREAD

**Issue by zkosanovic** [prebid/go-gpp#12]
The first 2 strings from the [GPP string examples section](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Core/Consent%20String%20Specification.md#gpp-string-examples) of the documentation give `error parsing GPP header` when I try to parse them using this library.

In the [GPP Consent String specification](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Core/Consent%20String%20Specification.md), it says:

> Note that neither the header nor the recommended encoding mechanism for a discrete section utilizes base64 encoding but rather a modified version of it.

I think maybe that is the reason why.

**Comment by zkosanovic** [comment]
For example, in the section [Header Examples](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Core/Consent%20String%20Specification.md#header-examples), the first example of an encoded header is string `DBABM`.

If we pass that string to the function [NewBitStreamFromBase64()](https://github.com/prebid/go-gpp/blob/main/util/bitstream.go#L20), it will fail with a message:
> illegal base64 data at input byte 4

On the other hand, the [iabgpp-java](https://github.com/IABTechLab/iabgpp-java) library uses a [custom decoding function](https://github.com/IABTechLab/iabgpp-java/blob/2b303d197e13a2097e613f026fc321b35f822e7c/iabgpp-encoder/src/main/java/com/iab/gpp/encoder/datatype/encoder/AbstractBase64UrlEncoder.java#L61) and it is able to decode this string properly:

```java
@Test
public void testDecode4() throws DecodingException {
  String decoded = base64UrlEncoder.decode("DBABM");
  System.out.println(decoded);
}
```

Output:
```
000011000001000000000001001100
``` 
I would say that this Go library needs similar custom decoding/encoding functions instead of using the regular base64.

I will look into this more and try to propose a solution, but would love some input on this in the meanwhile.

**Comment by SyntaxNode** [comment]
Thank you for the report. I'm looking into it.

**Comment by SyntaxNode** [comment]
The root cause is an issue decoding base64 url strings in which a quantum has only one character. The modification of base64 in GPP omits this concern since GPP is a bit stream instead of a byte stream. I'll get a fix up.

**Comment by SyntaxNode** [comment]
Actually, affects any incomplete quantum. I put up a PR to address the issue. Confirmed worked with parsing the GPP example strings from the docs.
