### ISSUE TITLE
VA Section's KnownChildSensitiveDataConsents should be `byte` value not `[]byte`

### ISSUE THREAD

**Issue by BernhardValenti** [prebid/go-gpp#8]
according to the spec VA should be handled like UT etc. and just have a single value: https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Sections/US-States/VA/GPP%20Extension:%20IAB%20Privacy%E2%80%99s%20Virginia%20Privacy%20Technical%20Specification.md

**Comment by hhhjort** [comment]
That is a good point. However a single entry slice is effectively a single value, even if it wastes a couple extra bytes of memory, and reusing the common core piece does promote interoperability between the different state consents. How do you feel about the tradeoff between maintaining more consistency in the datastructures for different states vs having a field that is cumbersome, and perhaps a bit confusing, yet still effectivey correct?

**Comment by BernhardValenti** [comment]
I was just worried that it's a bug to be honest. If it works as expected, I think it's totally fine. Someone else might also end up thinking it's a bug in the implementation, so maybe worth having a comment in the code to mention why it's done this way?

**Comment by hhhjort** [comment]
I created a PR for this: #10 , thanks.
